### PR TITLE
feat: introduce simple-action

### PR DESCRIPTION
**Pull request by GeoSot**
Extracting all Action content to trait, can give us the opportunity to use simple actions (inside resource edit page)

_note: needs to be documented too_

PS: Thanks for this package. it is the best, I have cheked till now 😄

### CODE REVIEW

**Comment by rmsramos** [comment]
This weekend I can review and merge, thank you for the contribution

**Comment by GeoSot** [comment]
Just a reminder here 😉

**Comment by rmsramos** [comment]
hi @GeoSot I didn't forget, I just lack the time to look at everything calmly and document it.
I'm going to organize myself so I don't let this week go by

**Comment by GeoSot** [comment]
If you need any help, please ping me up

**Review by rmsramos — APPROVED** [review]

**Pull request merged**
