### PR TITLE
Added Spanish Translations

### PR DESCRIPTION
**Pull request by edeoliv**
I have included the necessary translations for Spanish in the application. This enhancement ensures that Spanish-speaking users will have a better and more localized experience. The changes cover all the relevant sections of the application where translations were required.

Best regards
);

### CODE REVIEW

**Comment by rmsramos** [comment]
Is everything ok Elias? I launched a new release with something new, could you add the missing translations?
In advance, thank you for your collaboration.

**Comment by edeoliv** [comment]
Hello Romulo,

Of course, you can rely on me for whatever you need. I will close this PR and open another one with the new translations.

Best regards.

**Comment by edeoliv** [comment]
Hello Romulo,

I have pushed the latest changes as requested. Could you please review them when you have a moment? Thank you!

Best regards,

**Review by rmsramos — APPROVED** [review]
looking good

**Pull request merged**
